affinity_weight: 0.01
angle_for_fitscore: false
angle_match: true
as_exp: false
atom_weight: phore
auto_phorefp: false
batch_size: 10
boarder: true
by_radius: false
by_total: false
cache_path: ../data/cache
chembl_path: ../data/ChEMBL/
clash_cutoff:
- 1.0
- 2.0
- 3.0
- 4.0
- 5.0
clash_tolerance: 0.4
confidence_dropout: 0.0
confidence_mode: false
confidence_no_batchnorm: false
config: null
config_mode: model
consider_affinity: true
consider_ex: true
consider_norm: true
contact_weight: 1.0
contrastive: false
contrastive_model_dir: ''
cross_distance_embed_dim: 20
cross_distance_transition: true
cross_max_distance: 25.0
cudnn_benchmark: true
data_dir: ../data/PDBBind/
dataset: pdbbind
debug: false
delta_t: 0.05
dist_for_fitscore: false
distance_embed_dim: 20
dropout: 0.1
dynamic_coeff: 6.0
dynamic_max_cross: false
ema_rate: 0.999
embedding_scale: 10000
embedding_type: sinusoidal
epoch_from_infer: 400
ex_connected: true
ex_factor: -2.0
finetuning: true
fitscore: true
fitscore_cutoff: 0
flag: phoreDedup
freeze_epoch: 0
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
keep_origin_config: false
keep_update: false
limit_complexes: 0
load_optimizer: true
log_dir: ../results
lr: 0.001
lr_decay_factor: 0.9
matching: true
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_phore_num: 15
max_radius: 5.0
min_phore_num: 3
model_ckpt: last_model.pt
model_type: diff
multiple: true
n_epochs: 800
near_phore: false
neighbor_cutoff: 5.0
new: true
no_batch_norm: false
no_torsion: false
norm_by_ph: false
ns: 20
num_conformers: 1
num_conv_layers: 4
num_dataloader_workers: 10
num_inference_complexes: 1000
num_workers: 1
nv: 10
overwrite: false
phore_direction_transition: true
phore_path: null
phore_rule: true
phoretype_match: true
phoretype_match_transition: true
pin_memory: true
pose_weight: 5.0
pred_dis: true
pretrain_model_pt: null
project: diffphore_train
random_select: false
rate_from_infer: 0.6
readout: mean
reject: false
reject_rate: 0.3
remove_hs: true
restart_dir: null
restart_epoch: 53
restart_lr: null
return_node: true
ro5_filter: false
rot_sigma_max: 1.5
rot_sigma_min: 0.1
rot_weight: 0.33
run_dir: ../results/diffphore_warmuped_calibrated_ft
run_name: diffphore_warmuped_calibrated_ft
save_single: false
scale_by_sigma: true
scaler: 100.0
scheduler: plateau
scheduler_patience: 40
sigma_embed_dim: 20
sigmoid_for_fitscore: false
split_test: ../data/splits/timesplit_test
split_train: ../data/splits/timesplit_no_lig_overlap_train
split_val: ../data/splits/timesplit_no_lig_overlap_val
store_ranked_pose: false
test_sigma_intervals: false
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
tr_sigma_max: 5.0
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
train_number: 200000
train_propotion: 0.03
trioformer_layer: 2
type_for_fitscore: false
use_att: false
use_ema: true
use_las_constrains: true
use_phore_match_feat: true
use_phore_rule: true
use_sdf: true
use_second_order_repr: false
val_inference_freq: 5
valid_number: 10000
valid_propotion: 0.03
valid_warmup_number: 1000
valid_warmup_propotion: 0.03
w_decay: 0.0
warmup_epochs: 0
warmup_number: 20000
warmup_propotion: 0.03
zinc_path: ../data/ZINC/
